---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MLDKYT.
--- DateTime: 8/6/2021 7:21 PM
---

screen = {}

function screen.drawText(x, y, text) end
function screen.drawTextBox(x, y, w, h, text, h_align, v_align) end
function screen.drawClear() end
function screen.setColor(r, g, b, a) end
function screen.setColor(r, g, b) end
function screen.getWidth() end
function screen.getHeight() end
function screen.drawCircle(x, y, radius) end
function screen.drawCircleF(x, y, radius) end
function screen.drawRect(x, y, width, height) end
function screen.drawRectF(x, y, width, height) end
function screen.drawTriangle(x1, y1, x2, y2, x3, y3) end
function screen.drawTriangleF(x1, y1, x2, y2, x3, y3) end
function screen.setMapColorOcean(r, g, b, a) end
function screen.setMapColorShallows(r, g, b, a) end
function screen.setMapColorLand(r, g, b, a) end
function screen.setMapColorGrass(r, g, b, a) end
function screen.setMapColorSand(r, g, b, a) end
function screen.setMapColorSnow(r, g, b, a) end
function screen.drawMap(x, y, zoom) end

input = {}

function input.getNumber(index) end
function input.getBool(index) end

output = {}

function output.setNumber(index) end
function output.setBool(index) end

property = {}

function property.getBool(name) end
function property.getNumber(name) end
function property.getText(name) end

map = {}

function map.screenToMap(mapX, mapY, zoom, screenW, screenH, pixelX, pixelY) end
function map.mapToScreen(mapX, mapY, zoom, screenW, screenH, worldX, worldY) end

async = {}

function async.httpGet(port, url) end